import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fi: {
    // Dashboard
    balance: 'Saldo',
    monthly_payments: 'Kuukausimaksut',
    loans_credits: 'Lainat ja luotot',
    upcoming: 'Tulevat',
    transactions: 'Tapahtumat',
    recent_transactions: 'Viimeisimmät tapahtumat',
    no_transactions: 'Ei tapahtumia',
    all_transactions: 'Kaikki tapahtumat',
    upcoming_week: 'Tuleva viikko',
    
    // Payment status
    paid: 'Maksettu',
    unpaid: 'Maksamaton',
    paid_off: 'Maksettu pois',
    remaining: 'Jäljellä',
    total_debt: 'Velka yhteensä',
    original_amount: 'Alkuperäinen summa',
    current_amount: 'Nykyinen summa',
    
    // Categories
    food: 'Ruoka',
    food_dining: 'Ruoka ja ravintolat',
    transport: 'Liikenne',
    transportation: 'Liikenne',
    utilities: 'Laskut',
    shopping: 'Ostokset',
    loan: 'Laina',
    salary: 'Palkka',
    insurance: 'Vakuutus',
    subscriptions: 'Tilaukset',
    entertainment: 'Viihde',
    income: 'Tulo',
    other: 'Muu',
    
    // General
    total_bills: 'Laskut yhteensä',
    total_monthly: 'Yhteensä kuukausittain',
    show_less: 'Näytä vähemmän',
    more: 'lisää',
    view_all_payments: 'Näytä kaikki maksut',
    manage_loans_credits: 'Hallitse lainoja ja luottoja',
    no_monthly_payments: 'Ei kuukausimaksuja',
    due: 'Eräpäivä',
    
    // Notifications
    payment_processed: 'Maksu käsitelty',
    marked_as_paid: 'merkitty maksetuksi',
    payment_reversed: 'Maksu peruutettu',
    marked_as_unpaid: 'merkitty maksamattomaksi',
    insufficient_funds: 'Riittämätön saldo',
    required: 'vaaditaan',
    
    // Settings
    settings: 'Asetukset',
    account: 'Tili',
    profile: 'Profiili',
    notifications: 'Ilmoitukset',
    privacy_security: 'Yksityisyys ja turvallisuus',
    appearance_and_features: 'Ulkoasu ja ominaisuudet',
    appearance: 'Ulkoasu',
    backup: 'Varmuuskopiot',
    data: 'Tiedot',
    data_management: 'Tietojen hallinta',
    export_data: 'Vie tiedot',
    import_data: 'Tuo tiedot',
    clear_all_data: 'Tyhjennä kaikki tiedot',
    confirm_clear_all_data: 'Haluatko varmasti tyhjentää kaikki tiedot?',
    data_cleared: 'Tiedot tyhjennetty',
    backup_created: 'Varmuuskopio luotu',
    data_imported: 'Tiedot tuotu',
    error: 'Virhe',
    user: 'Käyttäjä',
    debts: 'Velat',
    financial_management_app: 'Taloudenhallintasovellus',
    version: 'Versio',
    change_password: 'Vaihda salasana',
    add_password: 'Lisää salasana',
    
    // Notification settings
    notification_settings: 'Ilmoitusasetukset',
    notification_preferences: 'Ilmoitusasetukset',
    upcoming_payments: 'Tulevat maksut',
    backup_reminders: 'Varmuuskopiomuistutukset',
    low_balance_alert: 'Alhaisen saldon hälytys',
    monthly_report: 'Kuukausiraportti',
    notify_before_payments_due: 'Ilmoita ennen maksuja',
    remind_to_create_backups: 'Muistuta varmuuskopioiden luomisesta',
    notify_when_balance_low: 'Ilmoita kun saldo on alhainen',
    monthly_summary_notification: 'Kuukausittainen yhteenveto',
    notify_days_before: 'Ilmoita päiviä ennen',
    day: 'päivä',
    days: 'päivää',
    threshold_amount: 'Kynnysarvo',
    important_note: 'Tärkeä huomautus',
    notification_permission_required: 'Ilmoitusoikeudet vaaditaan',
    save_settings: 'Tallenna asetukset',
    settings_saved: 'Asetukset tallennettu',
    notification_settings_updated: 'Ilmoitusasetukset päivitetty',
    
    // Appearance settings
    text_settings: 'Tekstiasetukset',
    screen_settings: 'Näyttöasetukset',
    
    // Backup settings
    backup_location: 'Varmuuskopion sijainti',
    choose_backup_folder: 'Valitse varmuuskopiokansio',
    
    // New missing translations
    home: 'Koti',
    back: 'Takaisin',
    cancel: 'Peruuta',
    save: 'Tallenna',
    delete: 'Poista',
    edit: 'Muokkaa',
    add: 'Lisää',
    remove: 'Poista',
    loading: 'Ladataan...',
    no_data: 'Ei tietoja',
    success: 'Onnistui',
    failed: 'Epäonnistui',
    
    // New translations for enhanced features
    search_transactions: 'Hae tapahtumia...',
    filter_by_type: 'Suodata tyypillä',
    date_range: 'Aikaväli',
    last_week: 'Viime viikko',
    last_month: 'Viime kuukausi', 
    last_quarter: 'Viime neljännes',
    last_year: 'Viime vuosi',
    from_date: 'Alkaen',
    to_date: 'Päättyen',
    showing_transactions: 'Näytetään {count} / {total} tapahtumaa',
    no_transactions_found: 'Ei tapahtumia löytynyt',
    transaction_updated: 'Tapahtuma päivitetty',
    transaction_deleted: 'Tapahtuma poistettu',
    failed_to_update_transaction: 'Tapahtuman päivittäminen epäonnistui',
    failed_to_delete_transaction: 'Tapahtuman poistaminen epäonnistui',
    confirm_delete_transaction: 'Haluatko varmasti poistaa tämän tapahtuman?',
    transactions_exported: 'Tapahtumat viety',
    edit_transaction: 'Muokkaa tapahtumaa',
    expense: 'Kulu',
    expenses: 'Kulut',
    
    // Category management
    edit_category: 'Muokkaa kategoriaa',
    category_details: 'Kategorian tiedot',
    category_name: 'Kategorian nimi',
    enter_category_name: 'Syötä kategorian nimi',
    category_description_placeholder: 'Kuvaus kategorialle...',
    category_color: 'Kategorian väri',
    maintenance_charge: 'Hoitovastike',
    maintenance_charge_description: 'Taloyhtiön hoitovastike',
    housing_company_expenditure: 'Taloyhtiön meno',
    housing_company_expenditure_description: 'Taloyhtiön yhteinen meno',
    monthly_payment_description: 'Kuukausittain toistuva maksu',
    save_changes: 'Tallenna muutokset',
    delete_category: 'Poista kategoria',
    category_updated: 'Kategoria päivitetty',
    category_deleted: 'Kategoria poistettu',
    updated_successfully: 'päivitetty onnistuneesti',
    deleted_successfully: 'poistettu onnistuneesti',
    category_name_required: 'Kategorian nimi vaaditaan',
    confirm_delete_category: 'Haluatko varmasti poistaa kategorian',
    
    // Category creator additions
    create_edit_category: 'Luo/muokkaa kategoriaa',
    existing_categories: 'Olemassa olevat kategoriat',
    no_categories: 'Ei kategorioita',
    create_new_category: 'Luo uusi kategoria',
    create_category: 'Luo kategoria',
    category_created: 'Kategoria luotu',
    created_successfully: 'luotu onnistuneesti',
    optional: 'valinnainen',
    
    // Settings and forms
    fill_required_fields: 'Täytä vaaditut kentät',
    credit_card_added: 'Luottokortti lisätty',
    calculated_values: 'Lasketut arvot',
    minimum_monthly_payment: 'Vähimmäiskuukausimaksu',
    estimated_total_with_interest: 'Arvioitu kokonaismäärä korkoineen',
    credit_card_name: 'Luottokortin nimi',
    credit_limit: 'Luottoraja',
    used_credit: 'Käytetty luotto',
    management_fee: 'Hallinnointipalkkio',
    minimum_payment_percent: 'Vähimmäismaksun prosentti',
    
    // Additional settings translations
    data_exported_successfully: 'Tiedot on viety onnistuneesti',
    data_imported_successfully: 'Tiedot on tuotu onnistuneesti',
    error_importing_data: 'Virhe tietojen tuonnissa',
    all_data_deleted: 'Kaikki tiedot on poistettu',
    confirm_clear_all: 'Haluatko varmasti tyhjentää kaikki tiedot?',
    notifications_enabled: 'Ilmoitukset käytössä',
    you_will_receive_notifications: 'Saat nyt ilmoituksia maksuista',
    permission_denied: 'Käyttöoikeus evätty',
    notifications_need_permission: 'Ilmoitukset tarvitsevat käyttöoikeuden',
    privacy_policy: 'Tietosuojakäytäntö',
    app_stores_data_locally: 'Tämä sovellus tallentaa tietosi paikallisesti laitteellesi. Mitään tietoja ei lähetetä ulkoisille palvelimille.',
    only_essential_cookies: 'Käytämme vain välttämättömiä evästeitä sovelluksen toiminnallisuuden varmistamiseksi.',
    analytics: 'Analytiikka',
    usage_data_collection: 'Käyttötietojen kerääminen',
    error_reports: 'Virheraportit',
    automatic_error_reports: 'Automaattiset virheraportti',
    visibility_settings: 'Näkyvyysasetukset',
    hide_balances: 'Piilota saldot',
    hide_balances_background: 'Piilota saldot taustasovelluksessa',
    screenshot_protection: 'Näyttökuvasuojaus',
    prevent_screenshots: 'Estä näyttökuvien ottaminen',
    appearance_features: 'Ulkoasu ja ominaisuudet',
    security_passwords: 'Turvallisuus ja salasanat',
    security_settings: 'Turvallisuusasetukset',
    financial_app: 'Taloudenhallinta-sovellus',
    due_date: 'Eräpäivä',
    add_credit_card: 'Lisää luottokortti',
    yearly_interest: 'Vuosikorko',
    
    // Appearance Settings
    font_size: 'Fonttikoko',
    small: 'Pieni',
    medium: 'Keskikokoinen',
    large: 'Suuri',
    high_contrast: 'Korkea kontrasti',
    better_visibility: 'Parempi näkyvyys',
    screen_brightness: 'Näytön kirkkaus',
    screen_timeout: 'Näytön aikakatkaisu',
    seconds_15: '15 sekuntia',
    seconds_30: '30 sekuntia',
    minute_1: '1 minuutti',
    minutes_5: '5 minuuttia',
    never: 'Ei koskaan',
    balance_on_lock_screen: 'Saldo lukitusnäytössä',
    show_balance_on_lock_screen: 'Näytä saldo lukitusnäytössä',
    animations: 'Animaatiot',
    use_transition_animations: 'Käytä siirtymäanimaatioita',
    theme: 'Teema',
    app_theme: 'Sovelluksen teema',
    light: 'Vaalea',
    dark: 'Tumma',
    setting_updated: 'Asetus päivitetty',
    
    // Backup Settings
    automatic_backup: 'Automaattinen varmuuskopiointi',
    create_backups_automatically: 'Luo varmuuskopioita automaattisesti',
    backup_frequency: 'Varmuuskopiointi väli',
    daily: 'Päivittäin',
    weekly: 'Viikoittain',
    monthly: 'Kuukausittain',
    storage_location: 'Tallennussijainti',
    downloads: 'Lataukset',
    documents: 'Dokumentit',
    custom_folder: 'Mukautettu kansio',
    selected: 'Valittu',
    file_compression: 'Tiedostojen pakkaus',
    compress_backup_files: 'Pienennä varmuuskopiotiedostoja',
    security: 'Turvallisuus',
    backup_password_optional: 'Varmuuskopion salasana (valinnainen)',
    enter_password_to_protect_backups: 'Anna salasana suojataksesi varmuuskopiot',
    cloud_storage: 'Pilvitallennus',
    save_backups_to_cloud: 'Tallenna varmuuskopiot pilveen',
    manual_backup: 'Manuaalinen varmuuskopiointi',
    create_backup_now: 'Luo varmuuskopio nyt',
    folder_selected: 'Kansio valittu',
    backups_will_be_saved_to_folder: 'Varmuuskopiot tallennetaan kansioon',
    not_supported: 'Ei tuettu',
    browser_does_not_support_folder_selection: 'Selaimesi ei tue kansion valintaa',
    folder_selection_failed: 'Kansion valinta epäonnistui',
    backup_downloaded_to_device: 'Varmuuskopio on ladattu laitteellesi',
    backup_setting_updated: 'Varmuuskopioasetus päivitetty',
    
    // Profile Settings (new)
    profile_settings: 'Profiiliasetukset',
    profile_information: 'Profiilitiedot',
    change_picture: 'Vaihda kuva',
    name: 'Nimi',
    email: 'Sähköposti',
    enter_name: 'Syötä nimesi',
    enter_email: 'Syötä sähköpostiosoitteesi',
    profile_updated: 'Profiili päivitetty',
    profile_saved_successfully: 'Profiilitiedot on tallennettu onnistuneesti',

    // Data Management (new)
    per_month: '/kk',
    danger_zone: 'Vaaravyöhyke',
    delete_all_data: 'Poista kaikki tiedot',
    item_deleted: 'on poistettu',
    loan_deleted: 'Laina poistettu',
    monthly_payment_deleted: 'Kuukausimaksu poistettu',
    confirm_delete_all: 'Haluatko varmasti poistaa kaikki tiedot? Tätä toimintoa ei voi peruuttaa.',
    app_reset: 'Sovellus on nollattu',

    // Security Settings (new)
    pin_code_4_digits: 'PIN-koodi (4 numeroa)',
    enable_pin: 'Ota PIN käyttöön',
    protect_with_pin: 'Suojaa sovellus PIN-koodilla',
    enable_fingerprint: 'Ota sormenjälki käyttöön',
    use_fingerprint_login: 'Käytä sormenjälkeä kirjautumiseen',
    two_factor_auth: 'Kaksivaiheinen tunnistus',
    use_authenticator: 'Käytä authenticator-sovellusta',
    security_actions: 'Turvatoiminnot',
    check_security: 'Tarkista turvallisuus',
    manage_data: 'Hallitse tietoja',
    
    // Security Messages (new)
    pin_error: 'PIN-koodin tulee olla 4 numeroa',
    pin_enabled: 'PIN käytössä',
    pin_set_successfully: 'PIN-koodi on asetettu onnistuneesti',
    pin_disabled: 'PIN poistettu',
    pin_disabled_description: 'PIN-koodi on poistettu käytöstä',
    fingerprint_not_supported: 'Sormenjälkitunnistus ei ole tuettu tässä selaimessa',
    fingerprint_enabled: 'Sormenjälki käytössä',
    fingerprint_activated: 'Sormenjälkitunnistus on aktivoitu',
    fingerprint_disabled: 'Sormenjälki pois käytöstä',
    fingerprint_disabled_description: 'Sormenjälkitunnistus on poistettu käytöstä',
    fingerprint_setup_failed: 'Sormenjälkitunnistuksen asetus epäonnistui',
    two_factor_enabled: '2FA käytössä',
    scan_qr_code: 'Skannaa QR-koodi authenticator-sovelluksella',
    two_factor_disabled: '2FA pois käytöstä',
    two_factor_disabled_description: 'Kaksivaiheinen tunnistus on poistettu käytöstä',
    two_factor_setup: '2FA Asetus:',
    download_authenticator: 'Lataa authenticator-sovellus (esim. Aegis, Google Authenticator)',
    scan_or_enter_key: 'Skannaa QR-koodi tai syötä avain manuaalisesti:',
    enter_6_digit_code: 'Syötä 6-numeroinen koodi authenticator-sovelluksesta',
    qr_code_url: 'QR-koodi URL:',
    password_change_coming: 'Salasanan vaihto -toiminto tulossa seuraavassa päivityksessä',
    pin_active: 'PIN-koodi käytössä',
    fingerprint_active: 'Sormenjälki käytössä',
    two_factor_active: '2FA käytössä',
    no_security_features: 'Ei turvallisuustoimia käytössä',

    // AddExpense additional translations (new)
    due_date_required: 'Eräpäivä vaaditaan tälle kategorialle',
    select_day: 'Valitse päivä',

    // Additional internationalization
    due_date_required_short: 'Eräpäivä vaaditaan',
    show_due_date_picker: 'Näytä eräpäivän valitsin tätä kategoriaa käytettäessä',
    this_week: 'Tämä viikko',
    year: 'Vuosi',
    no_payments_for_year: 'Ei maksuja vuodelle',
    loans_and_credits: 'Lainat ja luotot',
    no_payments: 'Ei maksuja',
    this_week_colon: 'Tällä viikolla:',
    month_colon: 'Kuukausi:',
    year_colon: 'Vuosi',
    type: 'Tyyppi',
    loan_name: 'Lainan nimi',
    total_loan_amount: 'Lainan kokonaissumma',
    remaining_amount: 'Jäljellä maksettava summa',
    monthly_payment_euro: 'Kuukausimaksu (€)',
    maintenance_fee_euro: 'Hoitokulu (€)',
    euribor_rate_percent: 'Euribor-korko (%)',
    personal_margin_percent: 'Henkilökohtainen marginaali (%)',
    months_remaining: 'Kuukausia jäljellä',
    months_placeholder: '60 kuukautta',
    annual_interest_percent: 'Vuosikorko (%)',
    minimum_payment_percent_fi: 'Vähimmäismaksuprosentti (%)',
    calculated_from_payment_data: 'Laskettu maksutiedoistasi:',
    estimated_euribor: 'Arvioitu Euribor: ',
    estimated_margin: 'Arvioitu marginaali: ',
    
    // Month names
    january: 'Tammikuu',
    february: 'Helmikuu',
    march: 'Maaliskuu',
    april: 'Huhtikuu',
    may: 'Toukokuu',
    june: 'Kesäkuu',
    july: 'Heinäkuu',
    august: 'Elokuu',
    september: 'Syyskuu',
    october: 'Lokakuu',
    november: 'Marraskuu',
    december: 'Joulukuu',
    
    // Analytics
    analytics_fi: 'Analytiikka',
    months: 'kuukautta',
    total_expenses: 'Kulut yhteensä',
    total_income: 'Tulot yhteensä',
    monthly_average: 'Kuukausikeskiarvo',
    savings_rate: 'Säästöprosentti',
    expense_trend: 'Kulutussuuntaus',
    category_breakdown: 'Kategoriajakauma',
    income_vs_expenses: 'Tulot vs. kulut',
    expenses_fi: 'Kulut',
    expense_forecast: 'Kulutusennuste',
    historical_data: 'Historiatiedot',
    forecasting: 'Ennustaminen',
    select_time_period: 'Valitse ajanjakso',
    
    // Quick Add and Forms
    quick_add: 'Pikalisäys',
    expense_added: 'Kulu lisätty',
    income_added: 'Tulo lisätty',
    expense_name: 'Kulujen nimi',
    income_name: 'Tulojen nimi',
    sum: 'Summa',
    select_category: 'Valitse kategoria',
    recurring_payment: 'Toistuva maksu',
    add_expense: 'Lisää kulu',
    add_income: 'Lisää tulo',
    add_loan: 'Lisää laina',
    loan_added: 'Laina lisätty',
    
    // Additional Categories
    bill: 'Lasku',
    subscription: 'Tilaus',
    paycheck: 'Palkka',
    loan_repayment: 'Lainan lyhennys',
    credit_repayment: 'Luottokortin maksu',
    credit_purchase: 'Luottokorttiostos',
    
    // Navigation and UI
    back_to_home: 'Takaisin kotiin',
    add_new_payment: 'Lisää uusi maksu',
    view_options: 'Näkymävaihtoehdot',
    month_navigation: 'Kuukausinavigointi',
    previous_month: 'Edellinen kuukausi',
    next_month: 'Seuraava kuukausi',
    total_amount: 'Kokonaissumma',
    
    // Data Management
    data_management_fi: 'Tietojen hallinta',
    export_data_fi: 'Vie tiedot',
    import_data_fi: 'Tuo tiedot',
    backup_and_restore: 'Varmuuskopiointi ja palautus',
    backup_restore_description: 'Luo varmuuskopioita tiedoistasi ja palauta ne toiselle laitteelle',
    export_description: 'Vie finanssitietosi varmuuskopioinnin tai analysoinnin vuoksi',
    import_description: 'Tuo tietoja toiselta laitteelta tai varmuuskopiosta',
    export_format: 'Viennin muoto',
    complete_backup_format: 'Täydellinen varmuuskopiomuoto',
    spreadsheet_compatible: 'Yhteensopiva laskentataulukoiden kanssa',
    export_json: 'Vie JSON',
    export_csv: 'Vie CSV',
    available_data: 'Saatavilla olevat tiedot',
    bills_data: 'Kuukausilaskut',
    loans: 'Lainat',
    categories: 'Kategoriat',
    export_successful: 'Vienti onnistui',
    export_failed: 'Vienti epäonnistui',
    data_export_success: 'Tiedot vietiin onnistuneesti',
    no_data_to_export: 'Ei vietäviä tietoja',
    exporting_data: 'Viedään tietoja',
    export_completed_successfully: 'Vienti suoritettu onnistuneesti',
    no_data_available_for_export: 'Ei vietäviä tietoja saatavilla',
    export_instructions: 'Vienti-ohjeet',
    json_full_backup: 'JSON: Täydellinen varmuuskopio kaikista tiedoista',
    csv_for_analysis: 'CSV: Sopii tietojen analysointiin',
    save_files_securely: 'Tallenna tiedostot turvalliseen paikkaan',
    regular_backups_recommended: 'Säännölliset varmuuskopiot suositeltuja',
    import_successful: 'Tuonti onnistui',
    import_failed: 'Tuonti epäonnistui',
    data_import_success: 'Tiedot tuotiin onnistuneesti',
    invalid_file_format: 'Virheellinen tiedostomuoto',
    only_json_files_supported: 'Vain JSON-tiedostot tuettu',
    select_file_to_import: 'Valitse tuotava tiedosto',
    json_files_only: 'Vain JSON-tiedostot',
    importing: 'Tuodaan',
    select_file: 'Valitse tiedosto',
    importing_data: 'Tuodaan tietoja',
    items_added: 'Kohteita lisätty',
    import_instructions: 'Tuonti-ohjeet',
    backup_current_data: 'Varmuuskopioi nykyiset tiedot ensin',
    use_exported_json_files: 'Käytä vain vietyjä JSON-tiedostoja',
    duplicate_entries_skipped: 'Kaksoiskappaleita ohitetaan',
    import_cannot_be_undone: 'Tuontia ei voi peruuttaa',
    export: 'Vie',
    import_action: 'Tuo',
    quick_actions: 'Pikavalinnat',
    create_backup: 'Luo varmuuskopio',
    restore_from_backup: 'Palauta varmuuskopiosta',
    retry: 'Yritä uudelleen',
  },
  en: {
    // Dashboard
    balance: 'Balance',
    monthly_payments: 'Monthly Payments',
    loans_credits: 'Loans & Credits',
    upcoming: 'Upcoming',
    transactions: 'Transactions',
    recent_transactions: 'Recent Transactions',
    no_transactions: 'No transactions',
    all_transactions: 'All Transactions',
    upcoming_week: 'Upcoming Week',
    
    // Payment status
    paid: 'Paid',
    unpaid: 'Unpaid',
    paid_off: 'Paid Off',
    remaining: 'Remaining',
    total_debt: 'Total Debt',
    original_amount: 'Original Amount',
    current_amount: 'Current Amount',
    
    // Categories
    food: 'Food',
    food_dining: 'Food & Dining',
    transport: 'Transport',
    transportation: 'Transportation',
    utilities: 'Utilities',
    shopping: 'Shopping',
    loan: 'Loan',
    salary: 'Salary',
    insurance: 'Insurance',
    subscriptions: 'Subscriptions',
    entertainment: 'Entertainment',
    income: 'Income',
    other: 'Other',
    
    // General
    total_bills: 'Total Bills',
    total_monthly: 'Total Monthly',
    show_less: 'Show Less',
    more: 'more',
    view_all_payments: 'View All Payments',
    manage_loans_credits: 'Manage Loans & Credits',
    no_monthly_payments: 'No monthly payments',
    due: 'Due',
    
    // Notifications
    payment_processed: 'Payment Processed',
    marked_as_paid: 'marked as paid',
    payment_reversed: 'Payment Reversed',
    marked_as_unpaid: 'marked as unpaid',
    insufficient_funds: 'Insufficient Funds',
    required: 'required',
    
    // Settings
    settings: 'Settings',
    account: 'Account',
    profile: 'Profile',
    notifications: 'Notifications',
    privacy_security: 'Privacy & Security',
    appearance_and_features: 'Appearance & Features',
    appearance: 'Appearance',
    backup: 'Backup',
    data: 'Data',
    data_management: 'Data Management',
    export_data: 'Export Data',
    import_data: 'Import Data',
    clear_all_data: 'Clear All Data',
    confirm_clear_all_data: 'Are you sure you want to clear all data?',
    data_cleared: 'Data Cleared',
    backup_created: 'Backup Created',
    data_imported: 'Data Imported',
    error: 'Error',
    user: 'User',
    debts: 'Debts',
    financial_management_app: 'Financial Management App',
    version: 'Version',
    change_password: 'Change Password',
    add_password: 'Add Password',
    
    // Notification settings 
    notification_settings: 'Notification Settings',
    notification_preferences: 'Notification Preferences',
    upcoming_payments: 'Upcoming Payments',
    backup_reminders: 'Backup Reminders',
    low_balance_alert: 'Low Balance Alert',
    monthly_report: 'Monthly Report',
    notify_before_payments_due: 'Notify before payments are due',
    remind_to_create_backups: 'Remind to create backups',
    notify_when_balance_low: 'Notify when balance is low',
    monthly_summary_notification: 'Monthly summary notification',
    notify_days_before: 'Notify days before',
    day: 'day',
    days: 'days',
    threshold_amount: 'Threshold Amount',
    important_note: 'Important Note',
    notification_permission_required: 'Notification permissions required',
    save_settings: 'Save Settings',
    settings_saved: 'Settings Saved',
    notification_settings_updated: 'Notification settings updated',
    
    // Appearance settings
    text_settings: 'Text Settings',
    screen_settings: 'Screen Settings',
    
    // Backup settings
    backup_location: 'Backup Location',
    choose_backup_folder: 'Choose Backup Folder',
    
    // New missing translations
    home: 'Home',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    remove: 'Remove',
    loading: 'Loading...',
    no_data: 'No data',
    success: 'Success',
    failed: 'Failed',
    
    // New translations for enhanced features
    search_transactions: 'Search transactions...',
    filter_by_type: 'Filter by type',
    date_range: 'Date Range',
    last_week: 'Last Week',
    last_month: 'Last Month',
    last_quarter: 'Last Quarter', 
    last_year: 'Last Year',
    from_date: 'From',
    to_date: 'To',
    showing_transactions: 'Showing {count} of {total} transactions',
    no_transactions_found: 'No transactions found',
    transaction_updated: 'Transaction Updated',
    transaction_deleted: 'Transaction Deleted',
    failed_to_update_transaction: 'Failed to update transaction',
    failed_to_delete_transaction: 'Failed to delete transaction',
    confirm_delete_transaction: 'Are you sure you want to delete this transaction?',
    transactions_exported: 'Transactions Exported',
    edit_transaction: 'Edit Transaction',
    expense: 'Expense',
    expenses: 'Expenses',
    
    // Category management
    edit_category: 'Edit Category',
    category_details: 'Category Details',
    category_name: 'Category Name',
    enter_category_name: 'Enter category name',
    category_description_placeholder: 'Description for category...',
    category_color: 'Category Color',
    maintenance_charge: 'Maintenance Charge',
    maintenance_charge_description: 'Housing company maintenance charge',
    housing_company_expenditure: 'Housing Company Expenditure',
    housing_company_expenditure_description: 'Housing company shared expense',
    monthly_payment_description: 'Monthly recurring payment', 
    save_changes: 'Save Changes',
    delete_category: 'Delete Category',
    category_updated: 'Category Updated',
    category_deleted: 'Category Deleted',
    updated_successfully: 'updated successfully',
    deleted_successfully: 'deleted successfully',
    category_name_required: 'Category name is required',
    confirm_delete_category: 'Are you sure you want to delete category',
    
    // Category creator additions
    create_edit_category: 'Create/Edit Category',
    existing_categories: 'Existing Categories',
    no_categories: 'No categories',
    create_new_category: 'Create New Category',
    create_category: 'Create Category',
    category_created: 'Category Created',
    created_successfully: 'created successfully',
    optional: 'optional',
    
    // Settings and forms
    fill_required_fields: 'Fill required fields',
    credit_card_added: 'Credit card added',
    calculated_values: 'Calculated values',
    minimum_monthly_payment: 'Minimum monthly payment',
    estimated_total_with_interest: 'Estimated total with interest',
    credit_card_name: 'Credit card name',
    credit_limit: 'Credit limit',
    used_credit: 'Used credit',
    management_fee: 'Management fee',
    minimum_payment_percent: 'Minimum payment percent',
    
    // Additional settings translations
    data_exported_successfully: 'Data exported successfully',
    data_imported_successfully: 'Data imported successfully',
    error_importing_data: 'Error importing data',
    all_data_deleted: 'All data deleted',
    confirm_clear_all: 'Are you sure you want to clear all data?',
    notifications_enabled: 'Notifications enabled',
    you_will_receive_notifications: 'You will now receive payment notifications',
    permission_denied: 'Permission denied',
    notifications_need_permission: 'Notifications require permission',
    privacy_policy: 'Privacy Policy',
    app_stores_data_locally: 'This app stores your data locally on your device. No data is sent to external servers.',
    only_essential_cookies: 'We only use essential cookies to ensure app functionality.',
    analytics: 'Analytics',
    usage_data_collection: 'Usage data collection',
    error_reports: 'Error reports',
    automatic_error_reports: 'Automatic error reports',
    visibility_settings: 'Visibility settings',
    hide_balances: 'Hide balances',
    hide_balances_background: 'Hide balances in background app',
    screenshot_protection: 'Screenshot protection',
    prevent_screenshots: 'Prevent taking screenshots',
    appearance_features: 'Appearance & Features',
    security_passwords: 'Security & Passwords',
    security_settings: 'Security Settings',
    financial_app: 'Financial Management App',
    due_date: 'Due Date',
    add_credit_card: 'Add Credit Card',
    yearly_interest: 'Yearly Interest',
    
    // Appearance Settings
    font_size: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    high_contrast: 'High Contrast',
    better_visibility: 'Better visibility',
    screen_brightness: 'Screen Brightness',
    screen_timeout: 'Screen Timeout',
    seconds_15: '15 seconds',
    seconds_30: '30 seconds',
    minute_1: '1 minute',
    minutes_5: '5 minutes',
    never: 'Never',
    balance_on_lock_screen: 'Balance on Lock Screen',
    show_balance_on_lock_screen: 'Show balance on lock screen',
    animations: 'Animations',
    use_transition_animations: 'Use transition animations',
    theme: 'Theme',
    app_theme: 'App Theme',
    light: 'Light',
    dark: 'Dark',
    setting_updated: 'Setting Updated',
    
    // Backup Settings
    automatic_backup: 'Automatic Backup',
    create_backups_automatically: 'Create backups automatically',
    backup_frequency: 'Backup Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    storage_location: 'Storage Location',
    downloads: 'Downloads',
    documents: 'Documents',
    custom_folder: 'Custom Folder',
    selected: 'Selected',
    file_compression: 'File Compression',
    compress_backup_files: 'Compress backup files',
    security: 'Security',
    backup_password_optional: 'Backup Password (Optional)',
    enter_password_to_protect_backups: 'Enter password to protect backups',
    cloud_storage: 'Cloud Storage',
    save_backups_to_cloud: 'Save backups to cloud',
    manual_backup: 'Manual Backup',
    create_backup_now: 'Create Backup Now',
    folder_selected: 'Folder Selected',
    backups_will_be_saved_to_folder: 'Backups will be saved to folder',
    not_supported: 'Not Supported',
    browser_does_not_support_folder_selection: 'Your browser does not support folder selection',
    folder_selection_failed: 'Folder selection failed',
    backup_downloaded_to_device: 'Backup has been downloaded to your device',
    backup_setting_updated: 'Backup Setting Updated',
    
    // Profile Settings (new)
    profile_settings: 'Profile Settings',
    profile_information: 'Profile Information',
    change_picture: 'Change Picture',
    enter_name: 'Enter your name',
    enter_email: 'Enter your email address',
    profile_updated: 'Profile Updated',
    profile_saved_successfully: 'Profile information has been saved successfully',

    // Data Management (new)
    per_month: '/mo',
    danger_zone: 'Danger Zone',
    delete_all_data: 'Delete All Data',
    item_deleted: 'has been deleted',
    loan_deleted: 'Loan Deleted',
    monthly_payment_deleted: 'Monthly Payment Deleted',
    confirm_delete_all: 'Are you sure you want to delete all data? This action cannot be undone.',
    app_reset: 'Application has been reset',

    // Security Settings (new)
    pin_code_4_digits: 'PIN Code (4 digits)',
    enable_pin: 'Enable PIN',
    protect_with_pin: 'Protect app with PIN code',
    enable_fingerprint: 'Enable Fingerprint',
    use_fingerprint_login: 'Use fingerprint for login',
    two_factor_auth: 'Two-Factor Authentication',
    use_authenticator: 'Use authenticator app',
    security_actions: 'Security Actions',
    check_security: 'Check Security',
    manage_data: 'Manage Data',
    
    // Security Messages (new)
    pin_error: 'PIN code must be 4 digits',
    pin_enabled: 'PIN Enabled',
    pin_set_successfully: 'PIN code has been set successfully',
    pin_disabled: 'PIN Disabled',
    pin_disabled_description: 'PIN code has been disabled',
    fingerprint_not_supported: 'Fingerprint authentication is not supported in this browser',
    fingerprint_enabled: 'Fingerprint Enabled',
    fingerprint_activated: 'Fingerprint authentication has been activated',
    fingerprint_disabled: 'Fingerprint Disabled',
    fingerprint_disabled_description: 'Fingerprint authentication has been disabled',
    fingerprint_setup_failed: 'Fingerprint setup failed',
    two_factor_enabled: '2FA Enabled',
    scan_qr_code: 'Scan QR code with authenticator app',
    two_factor_disabled: '2FA Disabled',
    two_factor_disabled_description: 'Two-factor authentication has been disabled',
    two_factor_setup: '2FA Setup:',
    download_authenticator: 'Download authenticator app (e.g. Aegis, Google Authenticator)',
    scan_or_enter_key: 'Scan QR code or enter key manually:',
    enter_6_digit_code: 'Enter 6-digit code from authenticator app',
    qr_code_url: 'QR Code URL:',
    password_change_coming: 'Password change feature coming in the next update',
    pin_active: 'PIN code active',
    fingerprint_active: 'Fingerprint active',
    two_factor_active: '2FA active',
    no_security_features: 'No security features enabled',

    // AddExpense additional translations (new)
    due_date_required: 'Due date is required for this category',
    select_day: 'Select day',

    // Additional internationalization
    due_date_required_short: 'Due date required',
    show_due_date_picker: 'Show due date picker when using this category',
    this_week: 'This week',
    no_payments_for_year: 'No payments for year',
    loans_and_credits: 'Loans and credits',
    no_payments: 'No payments',
    this_week_colon: 'This week:',
    month_colon: 'Month:',
    year_colon: 'Year',
    type: 'Type',
    loan_name: 'Loan name',
    total_loan_amount: 'Total loan amount',
    remaining_amount: 'Remaining amount',
    monthly_payment_euro: 'Monthly payment (€)',
    maintenance_fee_euro: 'Maintenance fee (€)',
    euribor_rate_percent: 'Euribor rate (%)',
    personal_margin_percent: 'Personal margin (%)',
    months_remaining: 'Months remaining',
    months_placeholder: '60 months',
    annual_interest_percent: 'Annual interest (%)',
    minimum_payment_percent_en: 'Minimum payment percent (%)',
    calculated_from_payment_data: 'Calculated from your payment data:',
    estimated_euribor: 'Estimated Euribor: ',
    estimated_margin: 'Estimated margin: ',
    
    // Month names
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    
    // Analytics
    analytics_en: 'Analytics',
    months: 'months',
    total_expenses: 'Total Expenses',
    total_income: 'Total Income',
    monthly_average: 'Monthly Average',
    savings_rate: 'Savings Rate',
    expense_trend: 'Expense Trend',
    category_breakdown: 'Category Breakdown',
    income_vs_expenses: 'Income vs. Expenses',
    expenses_en: 'Expenses',
    expense_forecast: 'Expense Forecast',
    historical_data: 'Historical Data',
    forecasting: 'Forecasting',
    select_time_period: 'Select Time Period',
    
    // Quick Add and Forms
    quick_add: 'Quick Add',
    expense_added: 'Expense Added',
    income_added: 'Income Added',
    expense_name: 'Expense Name',
    income_name: 'Income Name',
    sum: 'Amount',
    select_category: 'Select Category',
    recurring_payment: 'Recurring Payment',
    add_expense: 'Add Expense',
    add_income: 'Add Income',
    add_loan: 'Add Loan',
    loan_added: 'Loan Added',
    
    // Additional Categories
    bill: 'Bill',
    subscription: 'Subscription',
    paycheck: 'Paycheck',
    loan_repayment: 'Loan Repayment',
    credit_repayment: 'Credit Payment',
    credit_purchase: 'Credit Purchase',
    
    // Navigation and UI
    back_to_home: 'Back to Home',
    add_new_payment: 'Add New Payment',
    view_options: 'View Options',
    month_navigation: 'Month Navigation',
    previous_month: 'Previous Month',
    next_month: 'Next Month',
    total_amount: 'Total Amount',
    
    // Data Management
    data_management_en: 'Data Management',
    export_data_en: 'Export Data',
    import_data_en: 'Import Data',
    backup_and_restore: 'Backup & Restore',
    backup_restore_description: 'Create backups of your data and restore them on another device',
    export_description: 'Export your financial data for backup or analysis purposes',
    import_description: 'Import data from another device or backup file',
    export_format: 'Export Format',
    complete_backup_format: 'Complete backup format',
    spreadsheet_compatible: 'Spreadsheet compatible',
    export_json: 'Export JSON',
    export_csv: 'Export CSV',
    available_data: 'Available Data',
    bills_data: 'Monthly Bills',
    loans: 'Loans',
    categories: 'Categories',
    export_successful: 'Export Successful',
    export_failed: 'Export Failed',
    data_export_success: 'Data exported successfully',
    no_data_to_export: 'No data to export',
    exporting_data: 'Exporting data',
    export_completed_successfully: 'Export completed successfully',
    no_data_available_for_export: 'No data available for export',
    export_instructions: 'Export Instructions',
    json_full_backup: 'JSON: Full backup of all data',
    csv_for_analysis: 'CSV: Suitable for data analysis',
    save_files_securely: 'Save files in a secure location',
    regular_backups_recommended: 'Regular backups recommended',
    import_successful: 'Import Successful',
    import_failed: 'Import Failed',
    data_import_success: 'Data imported successfully',
    invalid_file_format: 'Invalid file format',
    only_json_files_supported: 'Only JSON files supported',
    select_file_to_import: 'Select file to import',
    json_files_only: 'JSON files only',
    importing: 'Importing',
    select_file: 'Select File',
    importing_data: 'Importing data',
    items_added: 'Items added',
    import_instructions: 'Import Instructions',
    backup_current_data: 'Backup current data first',
    use_exported_json_files: 'Use only exported JSON files',
    duplicate_entries_skipped: 'Duplicate entries will be skipped',
    import_cannot_be_undone: 'Import cannot be undone',
    export: 'Export',
    import_action: 'Import',
    quick_actions: 'Quick Actions',
    create_backup: 'Create Backup',
    restore_from_backup: 'Restore from Backup',
    retry: 'Retry',
  }
} as const;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fi');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
