import React, { createContext, useContext, useState, useEffect } from 'react';

interface Translation {
  [key: string]: {
    [key: string]: string;
  };
}

interface LanguageContextProps {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'fi',
  setLanguage: () => {},
  t: (key: string) => key,
});

const translations: Translation = {
  fi: {
    balance: 'Saldo',
    expenses: 'Menot',
    income: 'Tulot',
    total: 'Yhteensä',
    settings: 'Asetukset',
    profile: 'Profiili',
    backup: 'Varmuuskopio',
    import: 'Tuo',
    export: 'Vie',
    reset: 'Nollaa',
    name: 'Nimi',
    email: 'Sähköposti',
    edit_profile: 'Muokkaa profiilia',
    save: 'Tallenna',
    cancel: 'Peruuta',
    error: 'Virhe',
    fill_required_fields: 'Täytä kaikki pakolliset kentät',
    expense_added: 'Kulu lisätty',
    income_added: 'Tulo lisätty',
    add_expense: 'Lisää kulu',
    add_income: 'Lisää tulo',
    sum: 'Summa',
    category: 'Kategoria',
    type: 'Tyyppi',
    expense_name: 'Kulun nimi',
    select_category: 'Valitse kategoria',
    food: 'Ruoka',
    transport: 'Liikenne',
    entertainment: 'Viihde',
    bill: 'Lasku',
    insurance: 'Vakuutus',
    subscription: 'Tilaus',
    other: 'Muu',
    paycheck: 'Palkka',
    add_income_title: 'Lisää tulo',
    add_expense_title: 'Lisää kulu',
    income_name: 'Tulon nimi',
    expense: 'Kulu',
    monthly_payment_checkbox: 'Kuukausittainen maksu',
    quick_add: 'Pikalisäys',
    add_loan: 'Lisää laina',
    loan_name: 'Lainan nimi',
    total_amount: 'Lainan määrä',
    current_amount: 'Nykyinen määrä',
    monthly_payment: 'Kuukausierä',
    interest_rate: 'Korko',
    euribor_rate: 'Euribor',
    personal_margin: 'Marginaali',
    management_fee: 'Tilinhoitomaksu',
    remaining_months: 'Jäljellä olevat kuukaudet',
    due_date: 'Eräpäivä',
    loan_added: 'Laina lisätty',
    remaining: 'Jäljellä',
    loan_bill_payment: 'Lainan lyhennys',
    credit_card_payment: 'Luottokorttimaksu',
    credit_purchase: 'Luotto-ostos',
    abbreviation: 'Lyhennys',
    total_credit: 'Luottoraja',
    credits_used: 'Käytetty luotto',
    minimum_payment_percent: 'Minimilyhennys (%)',
    self_payment: 'Itse maksettava',
    manage_loans_credits: 'Hallinnoi lainoja ja luottoja',
    loans_credits: 'Lainat & Luotot',
    loans_credits_list: 'Lista',
    add_new: 'Lisää uusi',
    no_loans_credits: 'Ei lainoja tai luottoja',
    loan: 'Laina',
    credit_card: 'Luottokortti',
    add_credit_card: 'Lisää luottokortti',
    credit_card_name: 'Luottokortin nimi',
    credit_limit: 'Luottoraja',
    used_credit: 'Käytetty luotto',
    credit_card_added: 'Luottokortti lisätty',
    interest: 'Korko',
    upcoming_week: 'Tuleva viikko',
    financial_overview: 'Taloudellinen katsaus',
    manage_expenses: 'Hallinnoi kuluja',
    create_edit_category: 'Luo/Muokkaa kategoriaa',
    current_balance: 'Nykyinen saldo',
    due: 'Erääntyy',
    view_all_payments: 'Näytä kaikki maksut',
    home: 'Koti',
    upcoming: 'Tulevat',
    add: 'Lisää',
    history: 'Historia',
    transactions: 'Tapahtumat',
    total_debt: 'Velkaa yhteensä',
    monthly_payments: 'Kuukausimaksut',
    recent_transactions: 'Viimeisimmät tapahtumat',
    no_transactions: 'Ei tapahtumia',
    calculated_values: 'Lasketut arvot',
    yearly_rate: 'Vuosikorko',
    leave_empty_for_auto_calculation: 'Jätä tyhjäksi automaattista laskentaa varten',
    minimum_monthly_payment: 'Kuukausittainen vähimmäismaksu',
    estimated_total_with_interest: 'Arvioitu kokonaissumma korkojen kanssa',
    yearly_interest: 'Vuosikorko',
    edit_loan: 'Muokkaa lainaa',
    edit_credit_card: 'Muokkaa luottokorttia',
    loan_updated: 'Laina päivitetty',
    updated_successfully: 'päivitetty onnistuneesti',
    total_payback: 'Takaisinmaksu yhteensä',
    total_interest: 'Korot yhteensä',
    existing_categories: 'Olemassa olevat kategoriat',
    no_categories: 'Ei kategorioita',
    create_new_category: 'Luo uusi kategoria',
    category_name_required: 'Kategorian nimi vaaditaan',
    category_created: 'Kategoria luotu',
    created_successfully: 'luotu onnistuneesti',
    optional: 'valinnainen',
    total_loan_amount: 'Lainan kokonaismäärä',
    amount_left_to_pay: 'Maksettava määrä jäljellä',
    months_left: 'Kuukausia jäljellä',
    estimated_interest_rate: 'Arvioitu korko',
    confirm_delete_category: 'Haluatko varmasti poistaa kategorian',
    total_bills: 'Laskuja yhteensä',
    this_month: 'Tässä kuussa',
    bills: 'laskua',
    save_changes: 'Tallenna muutokset',
    category_name: 'Kategorian nimi',
    enter_category_name: 'Syötä kategorian nimi',
    description: 'Kuvaus',
    category_description_placeholder: 'Kategorian kuvaus...',
    category_color: 'Kategorian väri',
    maintenance_charge: 'Yhtiövastike',
    housing_company_expenditure: 'Taloyhtiön meno',
    create_category: 'Luo kategoria',
    category_deleted: 'Kategoria poistettu',
    deleted_successfully: 'poistettu onnistuneesti',
    maintenance_charge_description: 'Merkitse jos kyseessä on yhtiövastike',
    housing_company_expenditure_description: 'Merkitse jos kyseessä on taloyhtiön meno',
    monthly_payment_description: 'Merkitse jos kyseessä on kuukausittainen maksu',
    paid: 'Maksettu',
    paid_off: 'Maksettu',
    original_amount: 'Alkuperäinen määrä',
    insufficient_funds: 'Riittämätön saldo',
    required: 'Vaaditaan',
    payment_processed: 'Maksu käsitelty',
    marked_as_paid: 'merkitty maksetuksi',
    payment_reversed: 'Maksu peruutettu',
    marked_as_unpaid: 'merkitty maksamattomaksi',
    no_monthly_payments: 'Ei kuukausimaksuja',
    show_less: 'Näytä vähemmän',
    more: 'lisää',
    monthly_summary: 'Kuukausittainen yhteenveto',
    total_monthly: 'Yhteensä kuukausittain'
  },
  en: {
    balance: 'Balance',
    expenses: 'Expenses',
    income: 'Income',
    total: 'Total',
    settings: 'Settings',
    profile: 'Profile',
    backup: 'Backup',
    import: 'Import',
    export: 'Export',
    reset: 'Reset',
    name: 'Name',
    email: 'Email',
    edit_profile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    error: 'Error',
    fill_required_fields: 'Fill in all required fields',
    expense_added: 'Expense added',
    income_added: 'Income added',
    add_expense: 'Add Expense',
    add_income: 'Add Income',
    sum: 'Sum',
    category: 'Category',
    type: 'Type',
    expense_name: 'Expense name',
    select_category: 'Select category',
    food: 'Food',
    transport: 'Transport',
    entertainment: 'Entertainment',
    bill: 'Bill',
    insurance: 'Insurance',
    subscription: 'Subscription',
    other: 'Other',
    paycheck: 'Paycheck',
    add_income_title: 'Add Income',
    add_expense_title: 'Add Expense',
    income_name: 'Income name',
    expense: 'Expense',
    monthly_payment_checkbox: 'Monthly payment',
    quick_add: 'Quick Add',
    add_loan: 'Add Loan',
    loan_name: 'Loan name',
    total_amount: 'Total amount',
    current_amount: 'Current amount',
    monthly_payment: 'Monthly payment',
    interest_rate: 'Interest rate',
    euribor_rate: 'Euribor',
    personal_margin: 'Personal margin',
    management_fee: 'Management fee',
    remaining_months: 'Remaining months',
    due_date: 'Due date',
    loan_added: 'Loan added',
    remaining: 'Remaining',
    loan_bill_payment: 'Loan bill payment',
    credit_card_payment: 'Credit card payment',
    credit_purchase: 'Credit purchase',
    abbreviation: 'Abbreviation',
    total_credit: 'Credit limit',
    credits_used: 'Credits used',
    minimum_payment_percent: 'Minimum payment (%)',
    self_payment: 'Self payment',
    manage_loans_credits: 'Manage Loans & Credits',
    loans_credits: 'Loans & Credits',
    loans_credits_list: 'List',
    add_new: 'Add New',
    no_loans_credits: 'No loans or credits',
    loan: 'Loan',
    credit_card: 'Credit Card',
    add_credit_card: 'Add Credit Card',
    credit_card_name: 'Credit Card Name',
    credit_limit: 'Credit Limit',
    used_credit: 'Used Credit',
    credit_card_added: 'Credit Card Added',
    interest: 'Interest',
    upcoming_week: 'Upcoming Week',
    financial_overview: 'Financial Overview',
    manage_expenses: 'Manage Expenses',
    create_edit_category: 'Create/Edit Category',
    current_balance: 'Current Balance',
    due: 'Due',
    view_all_payments: 'View All Payments',
    home: 'Home',
    upcoming: 'Upcoming',
    add: 'Add',
    history: 'History',
    transactions: 'Transactions',
    total_debt: 'Total Debt',
    monthly_payments: 'Monthly Payments',
    recent_transactions: 'Recent Transactions',
    no_transactions: 'No transactions',
    calculated_values: 'Calculated Values',
    yearly_rate: 'Yearly Rate',
    leave_empty_for_auto_calculation: 'Leave empty for auto calculation',
    minimum_monthly_payment: 'Minimum Monthly Payment',
    estimated_total_with_interest: 'Estimated Total with Interest',
    yearly_interest: 'Yearly Interest',
    edit_loan: 'Edit Loan',
    edit_credit_card: 'Edit Credit Card',
    loan_updated: 'Loan Updated',
    updated_successfully: 'updated successfully',
    total_payback: 'Total Payback',
    total_interest: 'Total Interest',
    existing_categories: 'Existing Categories',
    no_categories: 'No categories',
    create_new_category: 'Create New Category',
    category_name_required: 'Category name is required',
    category_created: 'Category Created',
    created_successfully: 'created successfully',
    optional: 'optional',
    total_loan_amount: 'Total Loan Amount',
    amount_left_to_pay: 'Amount Left to Pay',
    months_left: 'Months Left',
    estimated_interest_rate: 'Estimated Interest Rate',
    confirm_delete_category: 'Are you sure you want to delete category',
    total_bills: 'Total Bills',
    this_month: 'This Month',
    bills: 'bills',
    save_changes: 'Save Changes',
    category_name: 'Category Name',
    enter_category_name: 'Enter category name',
    description: 'Description',
    category_description_placeholder: 'Category description...',
    category_color: 'Category Color',
    maintenance_charge: 'Maintenance Charge',
    housing_company_expenditure: 'Housing Company Expenditure',
    create_category: 'Create Category',
    category_deleted: 'Category Deleted',
    deleted_successfully: 'deleted successfully',
    maintenance_charge_description: 'Mark if this is a maintenance charge',
    housing_company_expenditure_description: 'Mark if this is a housing company expenditure',
    monthly_payment_description: 'Mark if this is a monthly payment',
    paid: 'Paid',
    paid_off: 'Paid Off',
    original_amount: 'Original Amount',
    insufficient_funds: 'Insufficient Funds',
    required: 'Required',
    payment_processed: 'Payment Processed',
    marked_as_paid: 'marked as paid',
    payment_reversed: 'Payment Reversed',
    marked_as_unpaid: 'marked as unpaid',
    no_monthly_payments: 'No monthly payments',
    show_less: 'Show Less',
    more: 'more',
    monthly_summary: 'Monthly Summary',
    total_monthly: 'Total Monthly'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'fi');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  return useContext(LanguageContext);
};
